import { NextResponse } from "next/server";
import { getAdminDb } from "@/lib/firebase-admin";
import { Fixture } from "@/lib/api-football";
import { requireAdmin } from "@/lib/admin-auth";

export async function POST(
    request: Request,
    { params }: { params: Promise<{ id: string }> }
) {
    try {
        if (!await requireAdmin()) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        const { id } = await params;
        const { dateKey } = await request.json();

        if (!id || !dateKey) {
            return NextResponse.json({ error: "Missing ID or dateKey" }, { status: 400 });
        }

        // Manual analysis is intentionally disabled: deep analysis is generated by
        // the idempotent scheduled job, never a user request.
        const docRef = getAdminDb().collection("fixtures").doc(`football-${dateKey}-${id}`);
        const snap = await docRef.get();

        if (!snap.exists) {
            return NextResponse.json({ error: "Fixture not found in cache" }, { status: 404 });
        }

        const fixture = snap.data() as Fixture;
        return NextResponse.json({ success: true, fixture, message: "Analysis is generated on the next scheduled run." });

    } catch (error: any) {
        console.error("[Manual Analysis] Error:", error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
